-- SPDX-FileCopyrightText: 2016 The GOE Authors
-- SPDX-License-Identifier: Apache-2.0

set termout off feedback off serveroutput on lines 200
spool sql/create_offload_repo.tmp replace
begin
    dbms_output.put_line(q'{-- Script generated by create_offload_repo.sql}');
    dbms_output.put_line(q'{-- SPDX-FileCopyrightText: 2016 The GOE Authors}');
    dbms_output.put_line(q'{-- SPDX-License-Identifier: Apache-2.0}');
    if '&goe_repo_install' = 'Y' then
        dbms_output.put_line('@@install_offload_repo.sql');
    elsif '&goe_repo_upgrade' = 'Y' then
        dbms_output.put_line('@@upgrade_offload_repo.sql');
    end if;
end;
/
spool off
set termout on feedback on serveroutput off

@@create_offload_repo.tmp
