-- SPDX-FileCopyrightText: 2016 The GOE Authors
-- SPDX-License-Identifier: Apache-2.0

prompt Creating types...
@@create_offload_repo_types.sql
prompt Creating views...
@@create_offload_repo_views.sql
prompt Creating packages...
@@create_offload_repo_packages.sql
prompt Creating synonyms...
@@create_offload_repo_synonyms.sql
prompt Creating grants...
@@create_offload_repo_grants.sql
